pipeline:
  name: guestbook
  identifier: guestbook
  projectIdentifier: GitOps_Demo
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: guestbook
        identifier: guestbook
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          execution:
            steps:
              - step:
                  type: GitOpsUpdateReleaseRepo
                  name: Update Release Repo
                  identifier: Update_Release_Repo
                  spec:
                    variables:
                      - name: envName
                        type: String
                        value: <+env.name>
                  timeout: 10m
              - step:
                  type: HarnessApproval
                  name: Approval
                  identifier: approval_gate
                  spec:
                    approvalMessage: Please review the following information and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      userGroups:
                        - account.New_Demo_Group
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1d
              - step:
                  type: MergePR
                  name: Merge PR
                  identifier: mergePR
                  spec:
                    deleteSourceBranch: true
                  timeout: 10m
            rollbackSteps: []
          environment:
            environmentRef: <+input>
            deployToAll: <+input>
            environmentInputs: <+input>
            serviceOverrideInputs: <+input>
            gitOpsClusters: <+input>
          gitOpsEnabled: true
          service:
            serviceRef: guestbookgitops
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  variables:
                    - name: releaseTag
                      type: String
                      value: <+input>.allowedValues(k8s-v0.1,k8s-v0.2,k8s-v0.3,k8s-v0.4,k8s-v0.5,k8s-v0.6)
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        variables: []
