apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-gitops
spec:
  defaultBackend:
    service:
      name: hello-gitops
      port:
        number: 80
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: hello-gitops
              servicePort: http