apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-gitops
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: hello-gitops
            port:
              name: http
        path: /
        pathType: Prefix