apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-gitops
spec:
  defaultBackend:
    service:
      name: hello-gitops
      port:
        number: 8080
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-gitops
            port:
              number: 80