apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: default
images:
- name: hello-gitops
  newName: mansong/hello-gitops
  newTag: "11"
