apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-gitops
  name: hello-gitops-svc
spec:
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hello-gitops
  type: LoadBalancer